### ISSUE TITLE
網址無法重複開啟

### ISSUE THREAD

**Issue by yupog2003** [pcman-bbs/pcmanx#30]
環境：Archlinux 64 bit kernel 3.19.2-1-ARCH

How to reproduce : help->about->點選任何一個網址->等待firefox開啟後->回到pcmanx->回到firefox關掉->回到pcmanx->點選網址

發生狀況：沒有反應

預期行為：開啟連結

**Comment by HMKRL** [comment]
於 ubuntu 15.04(unity桌面)測試無此問題

**Comment by holishing** [comment]
問題無法按照 issue 提及步驟重現，此 issue 將被關閉，若仍需回報類似問題請附上更詳細的資訊 (如在終端機下執行 `pcmanx` 時會出現相關的 console log)，謝謝
