### ISSUE TITLE
site list: find

### ISSUE THREAD

**Issue by b88923509** [pcman-bbs/pcmanx#32]
site list裡的find功能，只能從選擇的目錄開始，一直找到遇到的第一個最底層子目錄，搜尋完不會跳到上層目錄的下一個子目錄繼續搜尋。
例如：我直接搜尋"批踢踢"，則找完"大同"的子目錄就停止了，所以會顯示找不到。除非我點"台大"的子目錄再搜尋。
(pcmanx:23449): Gtk-CRITICAL **: gtk_tree_store_iter_parent: assertion 'VALID_ITER (child, tree_store)' failed

**Comment by b88923509** [comment]
找到原因了
在sitelistdlg.cpp的OnSearch function裡
第179行 else if( !gtk_tree_model_iter_next( model, &it) )
若it沒有下一個時，會被設為invalid
造成第184行 if( !gtk_tree_model_iter_parent( model, &parent_it, &it ) ) 會錯誤
而第188行也有和第179行一樣的問題
於是我稍微做了些修改

**Comment by jserv** [comment]
Can you send pull request?

**Comment by b88923509** [comment]
#34

**Comment by jserv** [comment]
Merged in commit 1527bb1911427b4c3fae965fa1b7d6633266ff1b

Thanks for your contribution!
