### ISSUE TITLE
Emoticons didn't load properly

### ISSUE THREAD

**Issue by tnlin** [pcman-bbs/pcmanx#41]
In pcmanx/data/emoticons ,we can find the default Icons
But when I click Edit -> Emoticons ,It is empty
Environment：Ubuntu 14.04.2 LTS 64-Bit @ VirtualBox 4.3.20

**Comment by TakeshiTseng** [comment]
檢查看看 /usr/local/share/pcmanx/ 裡面有沒有 emoticons 檔案

**Comment by jserv** [comment]
It results from an insane installation. Not a real bug.
