### ISSUE TITLE
對分頁的右鍵操作不合使用者預期

### ISSUE THREAD

**Issue by wdv4758h** [pcman-bbs/pcmanx#44]
首先開啟好幾個分頁

![pcman-1](https://cloud.githubusercontent.com/assets/2716047/7005135/de9f3cbc-dca7-11e4-9f37-c52f34e6b282.png)

接著對最左邊現在沒有 focus 的分頁點右鍵，選擇關閉

![pcman-2](https://cloud.githubusercontent.com/assets/2716047/7005145/ff3f33e6-dca7-11e4-9f4f-139dd9f666fb.png)

接著跳出視窗確認

![pcman-3](https://cloud.githubusercontent.com/assets/2716047/7005164/20dfb836-dca8-11e4-9e9d-69a4fe82e720.png)

最後發現關掉的是 focus 的視窗，而非點右鍵那個位置的視窗

![pcman-4](https://cloud.githubusercontent.com/assets/2716047/7005155/15192fe6-dca8-11e4-959f-2dcb17cc2e4b.png)

**Comment by jserv** [comment]
Fixed as the above patches were merged.
