### ISSUE TITLE
MS Windows port?

### ISSUE THREAD

**Issue by Vdragon** [pcman-bbs/pcmanx#68]
## 參考資料
* [下載—PCMan BBS Project](http://pcman.ptt.cc/downloads.html)
* [PCMan's Blog: [閒聊] PCMan BBS 連線軟體全系列的發展史](http://pcmanx.blogspot.tw/2009/11/pcman-bbs_184.html)
* [pcman-bbs/pcman-windows: PCMan Windows](https://github.com/pcman-bbs/pcman-windows)
* [下載區 - pcman - OpenFoundry](http://www.openfoundry.org/of/projects/744/download)

根據官網上的連結目前的 Windows 版跟 GNU/Linux 版 PCMan 雖然使用者介面類似但是出自於不同的來源碼樹，是否有合併兩者〈也就是讓其中一個版本能夠跨平台到 MS Windows 平台〉的必要性？

**Comment by kidwm** [comment]
當然沒有這個必要，原本的 PCMan 就是 Windows 版啊。

共用函式庫的話有 libbbs 正在開發中。

**Comment by Vdragon** [comment]
目前狀況下非兩專案共享之部份的 feature 就會有差異，比方說目前 SSH 通訊協定只有(?) GNU/Linux 版本支援，MS Windows 版本是不支援的

當然這可以當作 Windows 版的 feature request，但是如果改由單一來源碼樹來建構兩平台的版本的話會這類型的問題會比較少
